version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install package
          command: pip install -e .[test] 
      - run:
          name: Run tests
          command: py.test tests.py
